// Dstl (c) Crown Copyright 2023
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.33.1
// source: sapient_msg/bsi_flex_335_v1_0/alert_ack.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertAck_AlertStatus int32

const (
	AlertAck_ALERT_STATUS_UNSPECIFIED AlertAck_AlertStatus = 0 // Reason not set
	AlertAck_ALERT_STATUS_ACCEPTED    AlertAck_AlertStatus = 1 // Alert accepted
	AlertAck_ALERT_STATUS_REJECTED    AlertAck_AlertStatus = 2 // Alert rejected
	AlertAck_ALERT_STATUS_CANCELLED   AlertAck_AlertStatus = 3 // Alert cancelled
)

// Enum value maps for AlertAck_AlertStatus.
var (
	AlertAck_AlertStatus_name = map[int32]string{
		0: "ALERT_STATUS_UNSPECIFIED",
		1: "ALERT_STATUS_ACCEPTED",
		2: "ALERT_STATUS_REJECTED",
		3: "ALERT_STATUS_CANCELLED",
	}
	AlertAck_AlertStatus_value = map[string]int32{
		"ALERT_STATUS_UNSPECIFIED": 0,
		"ALERT_STATUS_ACCEPTED":    1,
		"ALERT_STATUS_REJECTED":    2,
		"ALERT_STATUS_CANCELLED":   3,
	}
)

func (x AlertAck_AlertStatus) Enum() *AlertAck_AlertStatus {
	p := new(AlertAck_AlertStatus)
	*p = x
	return p
}

func (x AlertAck_AlertStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertAck_AlertStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_enumTypes[0].Descriptor()
}

func (AlertAck_AlertStatus) Type() protoreflect.EnumType {
	return &file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_enumTypes[0]
}

func (x AlertAck_AlertStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertAck_AlertStatus.Descriptor instead.
func (AlertAck_AlertStatus) EnumDescriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_rawDescGZIP(), []int{0, 0}
}

// [START messages]
type AlertAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlertId     string               `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`                                                                      // ULID for the message
	AlertStatus AlertAck_AlertStatus `protobuf:"varint,2,opt,name=alert_status,json=alertStatus,proto3,enum=sapient_msg.bsi_flex_335_v1_0.AlertAck_AlertStatus" json:"alert_status,omitempty"` // State of the information in this message
	Reason      *string              `protobuf:"bytes,3,opt,name=reason,proto3,oneof" json:"reason,omitempty"`                                                                                 // Reason why alert was not accepted
}

func (x *AlertAck) Reset() {
	*x = AlertAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertAck) ProtoMessage() {}

func (x *AlertAck) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertAck.ProtoReflect.Descriptor instead.
func (*AlertAck) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_rawDescGZIP(), []int{0}
}

func (x *AlertAck) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *AlertAck) GetAlertStatus() AlertAck_AlertStatus {
	if x != nil {
		return x.AlertStatus
	}
	return AlertAck_ALERT_STATUS_UNSPECIFIED
}

func (x *AlertAck) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

var File_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto protoreflect.FileDescriptor

var file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x73, 0x61, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x2f, 0x62, 0x73,
	0x69, 0x5f, 0x66, 0x6c, 0x65, 0x78, 0x5f, 0x33, 0x33, 0x35, 0x5f, 0x76, 0x31, 0x5f, 0x30, 0x2f,
	0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1d, 0x73, 0x61, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x62, 0x73, 0x69,
	0x5f, 0x66, 0x6c, 0x65, 0x78, 0x5f, 0x33, 0x33, 0x35, 0x5f, 0x76, 0x31, 0x5f, 0x30, 0x22, 0xa4,
	0x02, 0x0a, 0x08, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x61,
	0x6c, 0x65, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x6c, 0x65, 0x72, 0x74, 0x49, 0x64, 0x12, 0x56, 0x0a, 0x0c, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x33, 0x2e, 0x73,
	0x61, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x62, 0x73, 0x69, 0x5f, 0x66,
	0x6c, 0x65, 0x78, 0x5f, 0x33, 0x33, 0x35, 0x5f, 0x76, 0x31, 0x5f, 0x30, 0x2e, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x41, 0x63, 0x6b, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x0b, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x22, 0x7d, 0x0a, 0x0b, 0x41,
	0x6c, 0x65, 0x72, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x18, 0x41, 0x4c,
	0x45, 0x52, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x4c, 0x45, 0x52,
	0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1a,
	0x0a, 0x16, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43,
	0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x50, 0x0a, 0x23, 0x75, 0x6b, 0x2e, 0x67, 0x6f, 0x76, 0x2e,
	0x64, 0x73, 0x74, 0x6c, 0x2e, 0x73, 0x61, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x6d, 0x73, 0x67, 0x2e,
	0x62, 0x73, 0x69, 0x66, 0x6c, 0x65, 0x78, 0x33, 0x33, 0x35, 0x76, 0x31, 0x42, 0x0d, 0x41, 0x6c,
	0x65, 0x72, 0x74, 0x41, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x18, 0x73,
	0x61, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x61, 0x70, 0x69, 0x65,
	0x6e, 0x74, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_rawDescData = file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_rawDesc
)

func file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_rawDescData = protoimpl.X.CompressGZIP(file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_rawDescData)
	})
	return file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_goTypes = []interface{}{
	(AlertAck_AlertStatus)(0), // 0: sapient_msg.bsi_flex_335_v1_0.AlertAck.AlertStatus
	(*AlertAck)(nil),          // 1: sapient_msg.bsi_flex_335_v1_0.AlertAck
}
var file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_depIdxs = []int32{
	0, // 0: sapient_msg.bsi_flex_335_v1_0.AlertAck.alert_status:type_name -> sapient_msg.bsi_flex_335_v1_0.AlertAck.AlertStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_init() }
func file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_init() {
	if File_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_depIdxs,
		EnumInfos:         file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_enumTypes,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto = out.File
	file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_rawDesc = nil
	file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v1_0_alert_ack_proto_depIdxs = nil
}
