// Dstl (c) Crown Copyright 2023
//
// [START declaration]

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.33.1
// source: sapient_msg/bsi_flex_335_v1_0/registration_ack.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// [START messages]
type RegistrationAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acceptance        bool    `protobuf:"varint,1,opt,name=acceptance,proto3" json:"acceptance,omitempty"`                                               // This value shall be 0 if the registration is rejected, or 1 if the registration is accepted
	AckResponseReason *string `protobuf:"bytes,2,opt,name=ack_response_reason,json=ackResponseReason,proto3,oneof" json:"ack_response_reason,omitempty"` // This field can be used to communicate the reason for non-registration
}

func (x *RegistrationAck) Reset() {
	*x = RegistrationAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationAck) ProtoMessage() {}

func (x *RegistrationAck) ProtoReflect() protoreflect.Message {
	mi := &file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationAck.ProtoReflect.Descriptor instead.
func (*RegistrationAck) Descriptor() ([]byte, []int) {
	return file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationAck) GetAcceptance() bool {
	if x != nil {
		return x.Acceptance
	}
	return false
}

func (x *RegistrationAck) GetAckResponseReason() string {
	if x != nil && x.AckResponseReason != nil {
		return *x.AckResponseReason
	}
	return ""
}

var File_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto protoreflect.FileDescriptor

var file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_rawDesc = []byte{
	0x0a, 0x34, 0x73, 0x61, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x2f, 0x62, 0x73,
	0x69, 0x5f, 0x66, 0x6c, 0x65, 0x78, 0x5f, 0x33, 0x33, 0x35, 0x5f, 0x76, 0x31, 0x5f, 0x30, 0x2f,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x63, 0x6b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x73, 0x61, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x6d, 0x73, 0x67, 0x2e, 0x62, 0x73, 0x69, 0x5f, 0x66, 0x6c, 0x65, 0x78, 0x5f, 0x33, 0x33, 0x35,
	0x5f, 0x76, 0x31, 0x5f, 0x30, 0x22, 0x7e, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x13, 0x61, 0x63, 0x6b, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x11, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x16, 0x0a,
	0x14, 0x5f, 0x61, 0x63, 0x6b, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x57, 0x0a, 0x23, 0x75, 0x6b, 0x2e, 0x67, 0x6f, 0x76, 0x2e,
	0x64, 0x73, 0x74, 0x6c, 0x2e, 0x73, 0x61, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x6d, 0x73, 0x67, 0x2e,
	0x62, 0x73, 0x69, 0x66, 0x6c, 0x65, 0x78, 0x33, 0x33, 0x35, 0x76, 0x31, 0x42, 0x14, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x6b, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x18, 0x73, 0x61, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x73, 0x61, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_rawDescOnce sync.Once
	file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_rawDescData = file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_rawDesc
)

func file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_rawDescGZIP() []byte {
	file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_rawDescOnce.Do(func() {
		file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_rawDescData = protoimpl.X.CompressGZIP(file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_rawDescData)
	})
	return file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_rawDescData
}

var file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_goTypes = []interface{}{
	(*RegistrationAck)(nil), // 0: sapient_msg.bsi_flex_335_v1_0.RegistrationAck
}
var file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_init() }
func file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_init() {
	if File_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_goTypes,
		DependencyIndexes: file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_depIdxs,
		MessageInfos:      file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_msgTypes,
	}.Build()
	File_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto = out.File
	file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_rawDesc = nil
	file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_goTypes = nil
	file_sapient_msg_bsi_flex_335_v1_0_registration_ack_proto_depIdxs = nil
}
